import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 text-gray-900 antialiased dark:bg-gray-900 dark:text-gray-100"
      >
        <main className="flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-grow">{children}</div>
        </main>
      </body>
    </html>
  );
}
